### ISSUE TITLE
getCababilities/getObservation only works for the first request

### ISSUE THREAD

**Issue by bcalton** [asascience-open/ncSOS#140]
Hi,

I am using thredds 4.3.22 and I have installed ncSOS RC8-2 and I have problem where only the first request after starting or reloading thredds works.

Requesting the URL 
http://vortex4.npm.ac.uk:8080/thredds-restricted/sos/ks.nc?service=SOS&request=getCapabilities 
works the first time and returns a valid capabilities XML document, and the following appears in the thredsServlet.log:
```
2014-07-31T16:16:29.901 +0100 [    166499][       2] INFO  - threddsServlet - Remote host: 192.171.164.85 - Request: "GET /thredds-restricted/sos/ks.nc?service=SOS&request=getCapabilities HTTP/1.1"
2014-07-31T16:16:30.722 +0100 [    167320][       2] INFO  - threddsServlet - Request Completed - 200 - -1 - 821
```
However, if I request that same URL again I get an error saying `Unable to read the dataset's feature type. Reported as STATION; unable to process.` and the following appears in the log:
```
2014-07-31T16:18:55.532 +0100 [    312130][       4] INFO  - threddsServlet - Remote host: 192.171.164.85 - Request: "GET /thredds-restricted/sos/ks.nc?service=SOS&request=getCapabilities HTTP/1.1"
2014-07-31T16:18:55.562 +0100 [    312160][       4] ERROR - com.asascience.ncsos.service.BaseRequestHandler - Unknown feature type! STATION
```

The same is true of a getObservation request; requesting 
http://vortex4.npm.ac.uk:8080/thredds-restricted/sos/ks.nc?service=SOS&request=getObservation&version=1.0.0&observedProperty=original&offering=urn:ioos:station:deltares.nl:1147010_kinshasa&responseFormat=text%2Fxml%3Bschema%3D%22om%2F1.0.0%22&eventTime=2000-01-01T00:00:00Z/2000-12-31T23:59:00Z 
the first time returns the expected data, but subsequent requests produce an error saying `Internal Error in creating output for GetObservation request - java.lang.NullPointerException` and the logs says:
```
2014-07-31T16:28:24.187 +0100 [    527953][       4] INFO  - threddsServlet - Remote host: 192.171.164.85 - Request: "GET /thredds-restricted/sos/ks.nc?service=SOS&request=getObservation&version=1.0.0&observedProperty=original&offering=urn:ioos:station:deltares.nl:1147010_kinshasa&responseFormat=text%2Fxml%3Bschema%3D%22om%2F1.0.0%22&eventTime=2000-01-01T00:00:00Z/2000-12-31T23:59:00Z HTTP/1.1"
2014-07-31T16:28:24.198 +0100 [    527964][       4] ERROR - com.asascience.ncsos.service.BaseRequestHandler - Unknown feature type! STATION
2014-07-31T16:28:24.201 +0100 [    527967][       4] ERROR - com.asascience.ncsos.service.Parser - Internal Error in creating output for GetObservation request:
java.lang.NullPointerException
	at com.asascience.ncsos.go.GetObservationRequestHandler.checkProcedureValidity(GetObservationRequestHandler.java:422)
	at com.asascience.ncsos.go.GetObservationRequestHandler.<init>(GetObservationRequestHandler.java:149)
	at com.asascience.ncsos.service.Parser.enhanceGETRequest(Parser.java:204)
	at com.asascience.ncsos.controller.SosController.handleSOSRequest(SosController.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
...
```

Are you able to offer any insight as to where things might be going wrong? Many thanks

Ben Calton

**Comment by cheryldmorse** [comment]
Tested the Glider-DAC 2 netCDF files with the 4.5 THREDDS server and this issue can no longer be reproduced.
